export const colors = {
  primary: '#451ebb',
  primaryContainer: '#5d3fd3',
  onPrimary: '#ffffff',
  onPrimaryContainer: '#d8ceff',
  primaryFixed: '#e6deff',
  primaryFixedDim: '#cabeff',
  onPrimaryFixed: '#1c0062',
  onPrimaryFixedVariant: '#4723be',

  secondary: '#5f5e5e',
  secondaryContainer: '#e5e2e1',
  onSecondary: '#ffffff',
  onSecondaryContainer: '#656464',
  secondaryFixed: '#e5e2e1',
  secondaryFixedDim: '#c8c6c5',
  onSecondaryFixed: '#1c1b1b',
  onSecondaryFixedVariant: '#474646',

  tertiary: '#005015',
  tertiaryContainer: '#006b1f',
  onTertiary: '#ffffff',
  onTertiaryContainer: '#88ea89',
  tertiaryFixed: '#96f996',
  tertiaryFixedDim: '#7adc7d',
  onTertiaryFixed: '#002105',
  onTertiaryFixedVariant: '#005316',

  error: '#ba1a1a',
  errorContainer: '#ffdad6',
  onError: '#ffffff',
  onErrorContainer: '#93000a',

  surface: '#fcf9f8',
  surfaceBright: '#fcf9f8',
  surfaceDim: '#dcd9d9',
  surfaceVariant: '#e5e2e1',
  surfaceContainer: '#f0edec',
  surfaceContainerLow: '#f6f3f2',
  surfaceContainerHigh: '#ebe7e7',
  surfaceContainerHighest: '#e5e2e1',
  surfaceContainerLowest: '#ffffff',
  surfaceTint: '#6042d6',

  onSurface: '#1c1b1b',
  onSurfaceVariant: '#484554',
  onBackground: '#1c1b1b',
  background: '#fcf9f8',

  outline: '#797586',
  outlineVariant: '#c9c4d7',
  inverseSurface: '#313030',
  inverseOnSurface: '#f3f0ef',
  inversePrimary: '#cabeff',
};
